### ISSUE TITLE
Zellij and Gum failed to load on MacOS

### ISSUE THREAD

**Issue by FunctionalPerformanceSystems** [mustardamus/wandersage#1]
When running ./wandersage on MacOS
~/wandersage/src/bootstrap.sh: line 21: ${response,,}: bad substitution
./wandersage: line 40: ~/wandersage/bin/zellij: No such file or directory

**Comment by mustardamus** [comment]
Thanks for your report! Could you tell me your bash and MacOS version by running:

```shell
bash --version
sw_vers
```

**Comment by FunctionalPerformanceSystems** [comment]
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.

ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79

**Comment by aharabara-globant** [comment]
@mustardamus I did some checks on MacOS. Here is some feedback

1. *bad substitution* can be solved with this `response=$response | tr '[:upper:]' '[:lower:]' # lowercase`
2. a check if `gum` and `zelij` should be added, because right now on mac zelij will fail to be executed (`exec format error`, probably wrong binary)

Will provide more feedback later

**Comment by mustardamus** [comment]
Thanks so much for jumping in @aharabara-globant, and sorry for not getting back to you @FunctionalPerformanceSystems , I've been pretty busy.

I'll fix the "bad substitution" thing in the coming days, thanks for the hint. As for the bootstrapping, you are right, just for Linux x86_64 right now. Should check the arch (`uname -m`) and wether it's Linux or MacOS (`uname -s`) to determine the correct binary for Gum and Zellij. 

Further more I want to provide a Docker Image in the future.

**Comment by mustardamus** [comment]
@FunctionalPerformanceSystems @aharabara-globant I've updated the code to fix the bug and download correct binaries for Linux and MacOS. As I don't have access to a Mac, could you do me the favor and test it? Thank you.

**Comment by aharabara-globant** [comment]
Did a quick test:
1. Yes it works
2.code assume that `zellij` and `gum` can be present on the machine, but it still tries to use them from `$PROJECT/bin` folder which means it fails when `gum` or `zellij` are preinstalled on different machines.
Can Be solved with `else` clause in bootstrap:
<img width="970" alt="Screenshot 2024-11-11 at 08 39 00" src="https://github.com/user-attachments/assets/4f99d922-6182-4345-b990-cfff98504150">

3. This one I encounter often, but didn't have a chance to check 
<img width="407" alt="Screenshot 2024-11-11 at 08 33 25" src="https://github.com/user-attachments/assets/f7507afb-6f92-48a2-8eb7-0f51ab5b7f23">

P.S
if you are trying to get the amount of files in folder in `explorer.sh:9`, then you can go with 
`find $NOTEBOOKS -maxdepth 1 -type f -name '*.md' | wc -l | xargs`
where `wc -l` counts lines and `xargs` will trim whitespaces from resulting value.

4. When I try to open a folder without any files it fails, because the assumption is that folder is not empty:
<img width="760" alt="Screenshot 2024-11-11 at 08 50 06" src="https://github.com/user-attachments/assets/ebf613a1-e6b7-4adc-9457-ed193416799b">

**Comment by mustardamus** [comment]
Awesome @aharabara-globant! Thanks for the details.

1. Neat
2. Haha, totally missed that. Fixed.
3. Removed `-printf x` from `find` for counting files. Should be fixed.
4. Added check for 0,1,x files when loading from folder. Fixed.

I'm closing this issue. If you find anything else or have further remarks, please open a new issue. Thanks!
